import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#601938",
    paddingHorizontal: 20,
    paddingTop: 48,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    gap: 12,
  },
  backButton: {
    backgroundColor: "#F5B55A",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#E97E0C",
  },
  backButtonText: {
    color: "#601938",
    fontWeight: "900",
    fontSize: 14,
  },
  headerInfo: {
    flex: 1,
  },
  levelBadge: {
    color: "#E480BB",
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 1,
  },
  levelTitle: {
    color: "#F5B55A",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  content: {
    flex: 1,
  },
  wordContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: "#F5B55A",
    marginBottom: 16,
  },
  wordLabel: {
    color: "#E480BB",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 12,
  },
  wordSlots: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  wordSlot: {
    width: 60,
    height: 60,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "dashed",
  },
  wordSlotFilled: {
    backgroundColor: "rgba(245, 181, 90, 0.15)",
    borderColor: "#F5B55A",
    borderStyle: "solid",
  },
  wordSlotCorrect: {
    backgroundColor: "rgba(228, 128, 187, 0.2)",
    borderColor: "#E480BB",
  },
  wordSlotText: {
    color: "rgba(255, 255, 255, 0.3)",
    fontSize: 24,
    fontWeight: "900",
  },
  wordSlotTextFilled: {
    color: "#F5B55A",
  },
  wordSlotTextCorrect: {
    color: "#E480BB",
  },
  hintButton: {
    backgroundColor: "rgba(245, 181, 90, 0.15)",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(245, 181, 90, 0.3)",
    alignItems: "center",
    marginBottom: 16,
  },
  hintButtonText: {
    color: "#F5B55A",
    fontWeight: "700",
    fontSize: 14,
  },
  hintContainer: {
    backgroundColor: "rgba(245, 181, 90, 0.08)",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(245, 181, 90, 0.2)",
    marginBottom: 16,
  },
  hintText: {
    color: "#E480BB",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  syllablesContainer: {
    marginBottom: 16,
  },
  syllablesLabel: {
    color: "#E480BB",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  syllablesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "center",
  },
  syllableButton: {
    backgroundColor: "#F5B55A",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#E97E0C",
    minWidth: 60,
    alignItems: "center",
  },
  syllableText: {
    color: "#601938",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 1,
  },
  selectedContainer: {
    marginBottom: 16,
  },
  selectedLabel: {
    color: "#E480BB",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  selectedGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "center",
  },
  selectedSyllable: {
    backgroundColor: "rgba(245, 181, 90, 0.2)",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#F5B55A",
    minWidth: 60,
    alignItems: "center",
  },
  selectedSyllableText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 1,
  },
  feedbackContainer: {
    marginVertical: 12,
  },
  feedbackCorrect: {
    backgroundColor: "rgba(228, 128, 187, 0.15)",
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: "#E480BB",
    alignItems: "center",
  },
  feedbackWrong: {
    backgroundColor: "rgba(233, 126, 12, 0.15)",
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: "#E97E0C",
    alignItems: "center",
    marginVertical: 12,
  },
  feedbackEmoji: {
    fontSize: 40,
    marginBottom: 8,
  },
  feedbackTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 4,
  },
  feedbackText: {
    color: "#E480BB",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 12,
  },
  nextButton: {
    backgroundColor: "#F5B55A",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#E97E0C",
  },
  nextButtonText: {
    color: "#601938",
    fontWeight: "900",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  attemptsContainer: {
    alignItems: "center",
    marginVertical: 8,
  },
  attemptsText: {
    color: "#E480BB",
    fontSize: 14,
    fontWeight: "600",
  },
  resetButton: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    alignItems: "center",
    marginTop: 8,
  },
  resetButtonText: {
    color: "#E480BB",
    fontSize: 14,
    fontWeight: "600",
  },
});