import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#601938",
    paddingHorizontal: 20,
    paddingTop: 48,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  backButton: {
    backgroundColor: "#F5B55A",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#E97E0C",
    marginRight: 12,
  },
  backButtonText: {
    color: "#601938",
    fontWeight: "900",
    fontSize: 14,
  },
  headerTitle: {
    color: "#F5B55A",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: 1,
  },
  voiceControls: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  voiceButton: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.15)",
    alignItems: "center",
  },
  voiceButtonActive: {
    backgroundColor: "rgba(245, 181, 90, 0.2)",
    borderColor: "#F5B55A",
  },
  voiceButtonAll: {
    flex: 1,
  },
  voiceButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  scrollContent: {
    flex: 1,
  },
  progressContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginBottom: 20,
  },
  progressDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
  },
  progressDotActive: {
    backgroundColor: "#F5B55A",
    width: 24,
  },
  progressDotCompleted: {
    backgroundColor: "rgba(245, 181, 90, 0.4)",
  },
  // Card do Tutorial
  card: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 16,
    padding: 24,
    borderWidth: 2,
    borderColor: "#F5B55A",
    minHeight: 300,
    shadowColor: "#F5B55A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  cardTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  cardDescription: {
    color: "#E480BB",
    fontSize: 16,
    textAlign: "center",
    lineHeight: 24,
    fontWeight: "500",
  },
  // Demonstração visual do exercício
  demoContainer: {
    marginTop: 20,
    padding: 16,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(245, 181, 90, 0.2)",
  },
  demoTitle: {
    color: "#F5B55A",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 12,
    letterSpacing: 1,
  },
  demoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  demoSyllable: {
    backgroundColor: "#F5B55A",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#E97E0C",
    minWidth: 50,
    alignItems: "center",
  },
  demoSyllableText: {
    color: "#601938",
    fontWeight: "800",
    fontSize: 18,
  },
  demoSyllableHighlight: {
    backgroundColor: "#E480BB",
    borderColor: "#F5B55A",
  },
  demoSyllableHighlightText: {
    color: "#FFFFFF",
  },
  demoWord: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
  },
  demoWordPart: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  demoWordPartText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "700",
  },
  demoWordPartHighlight: {
    backgroundColor: "#F5B55A",
    borderColor: "#E97E0C",
  },
  demoWordPartHighlightText: {
    color: "#601938",
  },
  demoArrow: {
    color: "#F5B55A",
    fontSize: 24,
    fontWeight: "700",
    marginHorizontal: 8,
  },
  // Navegação
  navigation: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
  },
  navButton: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  navButtonDisabled: {
    opacity: 0.3,
  },
  navButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
  },
  stepCounter: {
    color: "#E480BB",
    fontSize: 14,
    fontWeight: "600",
  },
  playButton: {
    backgroundColor: "#F5B55A",
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
    borderWidth: 3,
    borderColor: "#E97E0C",
  },
  playButtonText: {
    color: "#601938",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 1,
  },
});